apiVersion: skaffold/v2beta14
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    useDockerCLI: true
    useBuildkit: true
    push: false
  artifacts:
    - image: rahulraz/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
